language: cpp

dist: bionic
sudo: required

matrix:
  include:
    - name: Static checks (clang-format)
      env: STATIC_CHECKS=yes
      os: linux
      compiler: clang

    - name: Linux module (clang, Godot 4.0)
      env: GDVER="4.0"
      os: linux
      compiler: clang

before_install:
  - sudo apt-get update -qq
  - sudo apt -y install libasound2-dev libgl1-mesa-dev libglu1-mesa-dev libx11-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev -q
  - sudo apt -y install clang-format-8 -q

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      pyenv global 3.8 system;
      pip3 install --user scons;
    fi
  - scons --version

script:
  - if [ "$STATIC_CHECKS" = "yes" ]; then
      bash ./.scripts/clang_format.sh;
    else
      if [ "$GDVER" = "3.2" ]; then
        bash ./.scripts/module_build_3.sh;
      else
        bash ./.scripts/module_build_4.sh;
      fi
    fi
